// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v7.35.0
// source: spacex_api/device/gnss.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeReference int32

const (
	TimeReference_TIME_GPS     TimeReference = 0
	TimeReference_TIME_GALILEO TimeReference = 1
	TimeReference_TIME_BEIDOU  TimeReference = 2
	TimeReference_TIME_GLONASS TimeReference = 3
)

// Enum value maps for TimeReference.
var (
	TimeReference_name = map[int32]string{
		0: "TIME_GPS",
		1: "TIME_GALILEO",
		2: "TIME_BEIDOU",
		3: "TIME_GLONASS",
	}
	TimeReference_value = map[string]int32{
		"TIME_GPS":     0,
		"TIME_GALILEO": 1,
		"TIME_BEIDOU":  2,
		"TIME_GLONASS": 3,
	}
)

func (x TimeReference) Enum() *TimeReference {
	p := new(TimeReference)
	*p = x
	return p
}

func (x TimeReference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeReference) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_gnss_proto_enumTypes[0].Descriptor()
}

func (TimeReference) Type() protoreflect.EnumType {
	return &file_spacex_api_device_gnss_proto_enumTypes[0]
}

func (x TimeReference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeReference.Descriptor instead.
func (TimeReference) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{0}
}

type SatelliteSystem int32

const (
	SatelliteSystem_SYS_GPS        SatelliteSystem = 0
	SatelliteSystem_SYS_GALILEO    SatelliteSystem = 1
	SatelliteSystem_SYS_GLONASS    SatelliteSystem = 2
	SatelliteSystem_SYS_BEIDOU     SatelliteSystem = 3
	SatelliteSystem_SYS_SBAS       SatelliteSystem = 4
	SatelliteSystem_SYS_QZSS       SatelliteSystem = 5
	SatelliteSystem_SYS_IRNSS      SatelliteSystem = 6
	SatelliteSystem_SYS_STARLINK   SatelliteSystem = 7
	SatelliteSystem_SYS_STARSHIELD SatelliteSystem = 8
)

// Enum value maps for SatelliteSystem.
var (
	SatelliteSystem_name = map[int32]string{
		0: "SYS_GPS",
		1: "SYS_GALILEO",
		2: "SYS_GLONASS",
		3: "SYS_BEIDOU",
		4: "SYS_SBAS",
		5: "SYS_QZSS",
		6: "SYS_IRNSS",
		7: "SYS_STARLINK",
		8: "SYS_STARSHIELD",
	}
	SatelliteSystem_value = map[string]int32{
		"SYS_GPS":        0,
		"SYS_GALILEO":    1,
		"SYS_GLONASS":    2,
		"SYS_BEIDOU":     3,
		"SYS_SBAS":       4,
		"SYS_QZSS":       5,
		"SYS_IRNSS":      6,
		"SYS_STARLINK":   7,
		"SYS_STARSHIELD": 8,
	}
)

func (x SatelliteSystem) Enum() *SatelliteSystem {
	p := new(SatelliteSystem)
	*p = x
	return p
}

func (x SatelliteSystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SatelliteSystem) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_gnss_proto_enumTypes[1].Descriptor()
}

func (SatelliteSystem) Type() protoreflect.EnumType {
	return &file_spacex_api_device_gnss_proto_enumTypes[1]
}

func (x SatelliteSystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SatelliteSystem.Descriptor instead.
func (SatelliteSystem) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{1}
}

type CoordinateFrame int32

const (
	CoordinateFrame_ITRF CoordinateFrame = 0
	CoordinateFrame_ECEF CoordinateFrame = 1
	CoordinateFrame_GTRF CoordinateFrame = 2
	CoordinateFrame_PZ90 CoordinateFrame = 3
)

// Enum value maps for CoordinateFrame.
var (
	CoordinateFrame_name = map[int32]string{
		0: "ITRF",
		1: "ECEF",
		2: "GTRF",
		3: "PZ90",
	}
	CoordinateFrame_value = map[string]int32{
		"ITRF": 0,
		"ECEF": 1,
		"GTRF": 2,
		"PZ90": 3,
	}
)

func (x CoordinateFrame) Enum() *CoordinateFrame {
	p := new(CoordinateFrame)
	*p = x
	return p
}

func (x CoordinateFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoordinateFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_gnss_proto_enumTypes[2].Descriptor()
}

func (CoordinateFrame) Type() protoreflect.EnumType {
	return &file_spacex_api_device_gnss_proto_enumTypes[2]
}

func (x CoordinateFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoordinateFrame.Descriptor instead.
func (CoordinateFrame) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{2}
}

type Measurement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeOfValidityNs int64           `protobuf:"varint,1,opt,name=time_of_validity_ns,json=timeOfValidityNs,proto3" json:"time_of_validity_ns,omitempty"`
	SatelliteSystem  SatelliteSystem `protobuf:"varint,2,opt,name=satellite_system,json=satelliteSystem,proto3,enum=SpaceX.API.Device.Gnss.SatelliteSystem" json:"satellite_system,omitempty"`
	Prn              int32           `protobuf:"varint,3,opt,name=prn,proto3" json:"prn,omitempty"`
	Pseudorange      *Pseudorange    `protobuf:"bytes,4,opt,name=pseudorange,proto3" json:"pseudorange,omitempty"`
	Ephemeris        *Ephemeris      `protobuf:"bytes,5,opt,name=ephemeris,proto3" json:"ephemeris,omitempty"`
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacex_api_device_gnss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{0}
}

func (x *Measurement) GetTimeOfValidityNs() int64 {
	if x != nil {
		return x.TimeOfValidityNs
	}
	return 0
}

func (x *Measurement) GetSatelliteSystem() SatelliteSystem {
	if x != nil {
		return x.SatelliteSystem
	}
	return SatelliteSystem_SYS_GPS
}

func (x *Measurement) GetPrn() int32 {
	if x != nil {
		return x.Prn
	}
	return 0
}

func (x *Measurement) GetPseudorange() *Pseudorange {
	if x != nil {
		return x.Pseudorange
	}
	return nil
}

func (x *Measurement) GetEphemeris() *Ephemeris {
	if x != nil {
		return x.Ephemeris
	}
	return nil
}

type Pseudorange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PseudorangeM          float64 `protobuf:"fixed64,1,opt,name=pseudorange_m,json=pseudorangeM,proto3" json:"pseudorange_m,omitempty"`
	PseudorangeVarianceM2 float32 `protobuf:"fixed32,2,opt,name=pseudorange_variance_m2,json=pseudorangeVarianceM2,proto3" json:"pseudorange_variance_m2,omitempty"`
}

func (x *Pseudorange) Reset() {
	*x = Pseudorange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacex_api_device_gnss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pseudorange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pseudorange) ProtoMessage() {}

func (x *Pseudorange) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pseudorange.ProtoReflect.Descriptor instead.
func (*Pseudorange) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{1}
}

func (x *Pseudorange) GetPseudorangeM() float64 {
	if x != nil {
		return x.PseudorangeM
	}
	return 0
}

func (x *Pseudorange) GetPseudorangeVarianceM2() float32 {
	if x != nil {
		return x.PseudorangeVarianceM2
	}
	return 0
}

type Ephemeris struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SvDataTime      *SatnavTime     `protobuf:"bytes,1,opt,name=sv_data_time,json=svDataTime,proto3" json:"sv_data_time,omitempty"`
	CoordinateFrame CoordinateFrame `protobuf:"varint,2,opt,name=coordinate_frame,json=coordinateFrame,proto3,enum=SpaceX.API.Device.Gnss.CoordinateFrame" json:"coordinate_frame,omitempty"`
	SvPosM          *Vector3        `protobuf:"bytes,3,opt,name=sv_pos_m,json=svPosM,proto3" json:"sv_pos_m,omitempty"`
	SvVelM          *Vector3        `protobuf:"bytes,4,opt,name=sv_vel_m,json=svVelM,proto3" json:"sv_vel_m,omitempty"`
}

func (x *Ephemeris) Reset() {
	*x = Ephemeris{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacex_api_device_gnss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ephemeris) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ephemeris) ProtoMessage() {}

func (x *Ephemeris) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ephemeris.ProtoReflect.Descriptor instead.
func (*Ephemeris) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{2}
}

func (x *Ephemeris) GetSvDataTime() *SatnavTime {
	if x != nil {
		return x.SvDataTime
	}
	return nil
}

func (x *Ephemeris) GetCoordinateFrame() CoordinateFrame {
	if x != nil {
		return x.CoordinateFrame
	}
	return CoordinateFrame_ITRF
}

func (x *Ephemeris) GetSvPosM() *Vector3 {
	if x != nil {
		return x.SvPosM
	}
	return nil
}

func (x *Ephemeris) GetSvVelM() *Vector3 {
	if x != nil {
		return x.SvVelM
	}
	return nil
}

type SatnavTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeekNumber    uint32        `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	SecondsOfWeek float64       `protobuf:"fixed64,2,opt,name=seconds_of_week,json=secondsOfWeek,proto3" json:"seconds_of_week,omitempty"`
	TimeReference TimeReference `protobuf:"varint,3,opt,name=time_reference,json=timeReference,proto3,enum=SpaceX.API.Device.Gnss.TimeReference" json:"time_reference,omitempty"`
}

func (x *SatnavTime) Reset() {
	*x = SatnavTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacex_api_device_gnss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatnavTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatnavTime) ProtoMessage() {}

func (x *SatnavTime) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatnavTime.ProtoReflect.Descriptor instead.
func (*SatnavTime) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{3}
}

func (x *SatnavTime) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *SatnavTime) GetSecondsOfWeek() float64 {
	if x != nil {
		return x.SecondsOfWeek
	}
	return 0
}

func (x *SatnavTime) GetTimeReference() TimeReference {
	if x != nil {
		return x.TimeReference
	}
	return TimeReference_TIME_GPS
}

type Vector3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacex_api_device_gnss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{4}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_spacex_api_device_gnss_proto protoreflect.FileDescriptor

var file_spacex_api_device_gnss_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x70, 0x61, 0x63, 0x65, 0x78, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x67, 0x6e, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x22, 0xaa, 0x02, 0x0a, 0x0b, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x13, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6f,
	0x66, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x4e, 0x73, 0x12, 0x52, 0x0a, 0x10, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69,
	0x74, 0x65, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x27, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69,
	0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x0f, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c,
	0x69, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x72, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x72, 0x6e, 0x12, 0x45, 0x0a, 0x0b, 0x70,
	0x73, 0x65, 0x75, 0x64, 0x6f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x2e, 0x50, 0x73, 0x65, 0x75, 0x64, 0x6f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0b, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x69, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41,
	0x50, 0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x2e, 0x45,
	0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x69, 0x73, 0x52, 0x09, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65,
	0x72, 0x69, 0x73, 0x22, 0x6a, 0x0a, 0x0b, 0x50, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x5f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x70, 0x73, 0x65, 0x75, 0x64,
	0x6f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x12, 0x36, 0x0a, 0x17, 0x70, 0x73, 0x65, 0x75, 0x64,
	0x6f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x15, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4d, 0x32, 0x22,
	0x9b, 0x02, 0x0a, 0x09, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x69, 0x73, 0x12, 0x44, 0x0a,
	0x0c, 0x73, 0x76, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50, 0x49,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x2e, 0x53, 0x61, 0x74,
	0x6e, 0x61, 0x76, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x0a, 0x73, 0x76, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x52, 0x0a, 0x10, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x0f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x73, 0x76, 0x5f, 0x70, 0x6f,
	0x73, 0x5f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x58, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x6e,
	0x73, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x06, 0x73, 0x76, 0x50, 0x6f,
	0x73, 0x4d, 0x12, 0x39, 0x0a, 0x08, 0x73, 0x76, 0x5f, 0x76, 0x65, 0x6c, 0x5f, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50,
	0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x06, 0x73, 0x76, 0x56, 0x65, 0x6c, 0x4d, 0x22, 0xa3, 0x01,
	0x0a, 0x0a, 0x53, 0x61, 0x74, 0x6e, 0x61, 0x76, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x77, 0x65, 0x65, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x77, 0x65, 0x65, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x26, 0x0a,
	0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x4f,
	0x66, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x4c, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x6e, 0x73, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x2a, 0x52, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x49, 0x4d,
	0x45, 0x5f, 0x47, 0x50, 0x53, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x49, 0x4d, 0x45, 0x5f,
	0x47, 0x41, 0x4c, 0x49, 0x4c, 0x45, 0x4f, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x49, 0x4d,
	0x45, 0x5f, 0x42, 0x45, 0x49, 0x44, 0x4f, 0x55, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x49,
	0x4d, 0x45, 0x5f, 0x47, 0x4c, 0x4f, 0x4e, 0x41, 0x53, 0x53, 0x10, 0x03, 0x2a, 0xa1, 0x01, 0x0a,
	0x0f, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x59, 0x53, 0x5f, 0x47, 0x50, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x59, 0x53, 0x5f, 0x47, 0x41, 0x4c, 0x49, 0x4c, 0x45, 0x4f, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x53, 0x59, 0x53, 0x5f, 0x47, 0x4c, 0x4f, 0x4e, 0x41, 0x53, 0x53, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x53, 0x59, 0x53, 0x5f, 0x42, 0x45, 0x49, 0x44, 0x4f, 0x55, 0x10, 0x03, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x59, 0x53, 0x5f, 0x53, 0x42, 0x41, 0x53, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x59, 0x53, 0x5f, 0x51, 0x5a, 0x53, 0x53, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x59, 0x53, 0x5f, 0x49, 0x52, 0x4e, 0x53, 0x53, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x59,
	0x53, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x4c, 0x49, 0x4e, 0x4b, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x59, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x53, 0x48, 0x49, 0x45, 0x4c, 0x44, 0x10, 0x08,
	0x2a, 0x39, 0x0a, 0x0f, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x54, 0x52, 0x46, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x45, 0x43, 0x45, 0x46, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x54, 0x52, 0x46, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x5a, 0x39, 0x30, 0x10, 0x03, 0x42, 0x17, 0x5a, 0x15, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x78, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spacex_api_device_gnss_proto_rawDescOnce sync.Once
	file_spacex_api_device_gnss_proto_rawDescData = file_spacex_api_device_gnss_proto_rawDesc
)

func file_spacex_api_device_gnss_proto_rawDescGZIP() []byte {
	file_spacex_api_device_gnss_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_gnss_proto_rawDescData = protoimpl.X.CompressGZIP(file_spacex_api_device_gnss_proto_rawDescData)
	})
	return file_spacex_api_device_gnss_proto_rawDescData
}

var file_spacex_api_device_gnss_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spacex_api_device_gnss_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_spacex_api_device_gnss_proto_goTypes = []interface{}{
	(TimeReference)(0),   // 0: SpaceX.API.Device.Gnss.TimeReference
	(SatelliteSystem)(0), // 1: SpaceX.API.Device.Gnss.SatelliteSystem
	(CoordinateFrame)(0), // 2: SpaceX.API.Device.Gnss.CoordinateFrame
	(*Measurement)(nil),  // 3: SpaceX.API.Device.Gnss.Measurement
	(*Pseudorange)(nil),  // 4: SpaceX.API.Device.Gnss.Pseudorange
	(*Ephemeris)(nil),    // 5: SpaceX.API.Device.Gnss.Ephemeris
	(*SatnavTime)(nil),   // 6: SpaceX.API.Device.Gnss.SatnavTime
	(*Vector3)(nil),      // 7: SpaceX.API.Device.Gnss.Vector3
}
var file_spacex_api_device_gnss_proto_depIdxs = []int32{
	1, // 0: SpaceX.API.Device.Gnss.Measurement.satellite_system:type_name -> SpaceX.API.Device.Gnss.SatelliteSystem
	4, // 1: SpaceX.API.Device.Gnss.Measurement.pseudorange:type_name -> SpaceX.API.Device.Gnss.Pseudorange
	5, // 2: SpaceX.API.Device.Gnss.Measurement.ephemeris:type_name -> SpaceX.API.Device.Gnss.Ephemeris
	6, // 3: SpaceX.API.Device.Gnss.Ephemeris.sv_data_time:type_name -> SpaceX.API.Device.Gnss.SatnavTime
	2, // 4: SpaceX.API.Device.Gnss.Ephemeris.coordinate_frame:type_name -> SpaceX.API.Device.Gnss.CoordinateFrame
	7, // 5: SpaceX.API.Device.Gnss.Ephemeris.sv_pos_m:type_name -> SpaceX.API.Device.Gnss.Vector3
	7, // 6: SpaceX.API.Device.Gnss.Ephemeris.sv_vel_m:type_name -> SpaceX.API.Device.Gnss.Vector3
	0, // 7: SpaceX.API.Device.Gnss.SatnavTime.time_reference:type_name -> SpaceX.API.Device.Gnss.TimeReference
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_spacex_api_device_gnss_proto_init() }
func file_spacex_api_device_gnss_proto_init() {
	if File_spacex_api_device_gnss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spacex_api_device_gnss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measurement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacex_api_device_gnss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pseudorange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacex_api_device_gnss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ephemeris); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacex_api_device_gnss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SatnavTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacex_api_device_gnss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spacex_api_device_gnss_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_gnss_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_gnss_proto_depIdxs,
		EnumInfos:         file_spacex_api_device_gnss_proto_enumTypes,
		MessageInfos:      file_spacex_api_device_gnss_proto_msgTypes,
	}.Build()
	File_spacex_api_device_gnss_proto = out.File
	file_spacex_api_device_gnss_proto_rawDesc = nil
	file_spacex_api_device_gnss_proto_goTypes = nil
	file_spacex_api_device_gnss_proto_depIdxs = nil
}
