// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v6.31.1
// source: spacex_api/device/account_shard.proto

package account_shard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountShard int32

const (
	AccountShard_ACCOUNT_SHARD_UNKNOWN AccountShard = 0
	AccountShard_ACCOUNT_SHARD_DEFAULT AccountShard = 1
	AccountShard_ACCOUNT_SHARD_INDIA   AccountShard = 2
)

// Enum value maps for AccountShard.
var (
	AccountShard_name = map[int32]string{
		0: "ACCOUNT_SHARD_UNKNOWN",
		1: "ACCOUNT_SHARD_DEFAULT",
		2: "ACCOUNT_SHARD_INDIA",
	}
	AccountShard_value = map[string]int32{
		"ACCOUNT_SHARD_UNKNOWN": 0,
		"ACCOUNT_SHARD_DEFAULT": 1,
		"ACCOUNT_SHARD_INDIA":   2,
	}
)

func (x AccountShard) Enum() *AccountShard {
	p := new(AccountShard)
	*p = x
	return p
}

func (x AccountShard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountShard) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_account_shard_proto_enumTypes[0].Descriptor()
}

func (AccountShard) Type() protoreflect.EnumType {
	return &file_spacex_api_device_account_shard_proto_enumTypes[0]
}

func (x AccountShard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountShard.Descriptor instead.
func (AccountShard) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_account_shard_proto_rawDescGZIP(), []int{0}
}

var File_spacex_api_device_account_shard_proto protoreflect.FileDescriptor

var file_spacex_api_device_account_shard_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x70, 0x61, 0x63, 0x65, 0x78, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e,
	0x41, 0x50, 0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2a, 0x5d, 0x0a, 0x0c, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x44, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x5f, 0x53, 0x48, 0x41, 0x52, 0x44, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x48, 0x41, 0x52,
	0x44, 0x5f, 0x49, 0x4e, 0x44, 0x49, 0x41, 0x10, 0x02, 0x42, 0x25, 0x5a, 0x23, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x78, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spacex_api_device_account_shard_proto_rawDescOnce sync.Once
	file_spacex_api_device_account_shard_proto_rawDescData = file_spacex_api_device_account_shard_proto_rawDesc
)

func file_spacex_api_device_account_shard_proto_rawDescGZIP() []byte {
	file_spacex_api_device_account_shard_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_account_shard_proto_rawDescData = protoimpl.X.CompressGZIP(file_spacex_api_device_account_shard_proto_rawDescData)
	})
	return file_spacex_api_device_account_shard_proto_rawDescData
}

var file_spacex_api_device_account_shard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spacex_api_device_account_shard_proto_goTypes = []interface{}{
	(AccountShard)(0), // 0: SpaceX.API.Device.AccountShard
}
var file_spacex_api_device_account_shard_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spacex_api_device_account_shard_proto_init() }
func file_spacex_api_device_account_shard_proto_init() {
	if File_spacex_api_device_account_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spacex_api_device_account_shard_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_account_shard_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_account_shard_proto_depIdxs,
		EnumInfos:         file_spacex_api_device_account_shard_proto_enumTypes,
	}.Build()
	File_spacex_api_device_account_shard_proto = out.File
	file_spacex_api_device_account_shard_proto_rawDesc = nil
	file_spacex_api_device_account_shard_proto_goTypes = nil
	file_spacex_api_device_account_shard_proto_depIdxs = nil
}
